"""story soft delete and version archived

Revision ID: af364d82e5be
Revises: a3b17345973b
Create Date: 2026-03-20 18:09:28.573012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af364d82e5be'
down_revision: Union[str, Sequence[str], None] = 'a3b17345973b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('story_versions', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_versions', 'is_archived')
    op.drop_column('stories', 'deleted_at')
    # ### end Alembic commands ###
